### ISSUE TITLE
Wrong rendered tiles for some tifs and zooms

### ISSUE THREAD

**Issue by Bulva** [geodesign/django-raster#18]
Hi,

I have some difficulties with generating tiles for some of my tif pictures. Tiles are not correctly generated for some reason. I attach screen with situation from Leaflet. I do not use legend and in raster layer log looks everything fine. I am using Django 1.10 and it is testing version, so it is on django development server

![django-raster-tiles](https://cloud.githubusercontent.com/assets/9295282/23187811/8c2a1e5e-f88c-11e6-8007-b1471e7b7dc8.png)

**Comment by yellowcap** [comment]
It is hard to guess what is going on, but since the parsing is successful and the raster displays as expected partially, it is probably a data issue not a software bug. 

The default django-raster rendering uses the pixel range from the metadata to create a "dynamic" colour scheme. So maybe the automatic legend does not work as expected for your raster. Here are a few suggestions/questions on what it could be:

Could you apply a legend and see if the problem also exists when you use a specific legend?

Does the raster display as expected for some zoom levels and not in others? Make sure your browser is not caching a previous version of the tiles. If you have displayed the same raster before, leaflet could be using cached tiles that were generated with a different legend.

**Comment by Bulva** [comment]
Yea, how you said. It must be problem with my tiffs. I tried to style layer in Geoserver and the result is the same as in django-raster (if I set legend). Only one color raster. Like on image:

![birds](https://cloud.githubusercontent.com/assets/9295282/23220676/0545854e-f923-11e6-8f2a-2781593d5d5e.png)
