### ISSUE TITLE
Demo in docker.

### ISSUE THREAD

**Issue by winsento** [geodesign/django-raster#25]
Im wrote simple demo project for django-raster based on docker. 
If this is of interest to you, I can transfer the repository.

https://github.com/winsento/django-raster-demo

I want to warn in the project there are parts that need improvement.

**Comment by yellowcap** [comment]
Thanks @winsento that looks really interesting! I have been thinking about doing such a demo project for a while, but never found time to do it.

Are you planning to continue improving the project?

I can help working on it so that once we are happy with its status we can transfer it and refer to it as the "official" demo or so.

**Comment by winsento** [comment]
@yellowcap Yes, I plan to make celery work and write a compose file so that postgres, django-raster-demo, redis, etc., start right away.
If you want to help, welcome.

At any time, I'm ready to transfer the repository.

**Comment by EverWinter23** [comment]
@winsento  @yellowcap  A docker demo would be so great!!!

**Comment by CARocha** [comment]
@yellowcap Hi, i try put color in my maps but fail each try, i find example but don't see any example, i install QGis and import raster is easy put color this is example
<img width="734" alt="Captura de pantalla 2019-09-05 a la(s) 22 55 18" src="https://user-images.githubusercontent.com/168115/64401915-4966eb00-d030-11e9-8345-7d37acb92cef.png">
but in my web project only see grayscale i try put the colors but impossible see:
<img width="657" alt="Captura de pantalla 2019-09-05 a la(s) 22 57 34" src="https://user-images.githubusercontent.com/168115/64402008-99de4880-d030-11e9-98b0-c45c3d624e8c.png">
where I can see an example that put color to the map?? with leaflet!!
this is my javascript:
<script type="text/javascript">
var map = L.map('main').setView([14.75643, -87.86453], 6);
var colors ={
    "1": "#e21cb4",
    "2": "#ffffff",
    "3": "#a86061",
    "4": "#c07f24",
    "5": "#315f62",
    "6": "#2d9790",
    "7": "#9e9e9e",
    "8": "#eae179",
}
// Openstreemap background tiles
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
// Your tiles
L.tileLayer('http://localhost:8000/raster/tiles/1/{z}/{x}/{y}.png', {
    attribution: 'Something'
}).addTo(map);
</script>

and this backend raster file saved
<img width="1356" alt="Captura de pantalla 2019-09-05 a la(s) 23 04 49" src="https://user-images.githubusercontent.com/168115/64402293-a3b47b80-d031-11e9-8f61-77faf5c87a02.png">

Any help I would appreciate it, I am a rookie on maps and I still don't understand many things

**Comment by yellowcap** [comment]
@CARocha you are almost there! To add color to the map, you can assign a Legend to your RasterLayer model. Go to  the http://localhost:8000/admin/raster/legend list and click on "add legend". There you can specify a legend, specifying the different "entries" with colors. Each "legend entry" has a "Semantic" (aka name), an "expression" (a value or value range for this name, in your case a single value because your raster is discrete), and a "color". The "code" column you can ignore, it can be used to tag or order the legend entries.

Here is an example from one of my legends:
![image](https://user-images.githubusercontent.com/901647/64416172-9f6a7b80-d08e-11e9-8e26-00a00c98f2bf.png)

After creating the legend, you have to assign it to the RasterLayer. Go to the admin of your raster layer, and select the legend you created. After that, the raster should render in the colors you selected. Note that any value not found in the Legend will simply be transparent in the rendering. So make sure you add one legend entry for each of your 1-9 values.

**Comment by CARocha** [comment]
@yellowcap thank works fine, by the way, i sorry for written in this issues!!

**Comment by yellowcap** [comment]
@CARocha glad this worked!
