### ISSUE TITLE
GDAL compatibility

### ISSUE THREAD

**Issue by jer-shiny** [geodesign/django-raster#5]
I'm not able to install django-raster with GDAL 1.9.2 (which is the gdal build supplied with my OS of CentOS 6.4)    It looks like django-raster is dependent on GDAL 1.10 or higher from the errors I'm getting, is that correct?  Any possible workarounds, besides doing a re-install to GDAL 1.10?
When I try to install, it appears the build tries to install GDAL 1.10 but cannot find the proper header files. 
Open to advice I'd really like to build this, it looks like a fantastic toolkit for what I need.  Thank you, and apologies if this is not posted in the proper place (as it is a request more than an 'issue'.)

**Comment by yellowcap** [comment]
That's right, the setup file is configured to require GDAL 1.10. This is because the GDAL Raster Driver is slow and less stable in GDAL 1.9. You could try to install the package without dependencies through `pip install django-raster --no-dependencies`. If you have the gdal package in your pythonpath, this could work as it will skip the gdal install. I guess the package would also work with GDAL 1.9, but it might be slower and I am not sure, so far I used only GDAL 1.10.

**Comment by mflaxman10** [comment]
Hi Daniel

Live users we don't know, very good!  

Meanwhile the potential tabular aggregation library I stumbled upon is this one:

http://square.github.io/crossfilter/

Not a recommendation - just FYI in case useful.   Just keeping track of these libraries could be a full time job!

Mike
