### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by ArnaudLevaufre** [geodesign/django-raster#8]
Hello,

It looks like a migration file is missing. I installed django-raster from the master with pip and added raster to my INSTALLED_APPS. Running the makemigrations command creates a new migration file for raster:

```
::::| ./manage.py makemigrations --dry-run
Migrations for 'raster':
  0032_auto_20160425_1328.py:
    - Alter field expression on legendentry
    - Alter field datatype on rasterlayer
    - Alter field max_zoom on rasterlayer
    - Alter field nodata on rasterlayer
    - Alter field rasterfile on rasterlayer
    - Alter field srid on rasterlayer
    - Alter field log on rasterlayerparsestatus
    - Alter field status on rasterlayerparsestatus
    - Alter field rasterfile on rasterlayerreprojected
```

**Comment by mflaxman10** [comment]
Hi Arnaud,

Thanks for finding this.  Daniel is out today, but should be able to 
take a look shortly.

Mike Flaxman

**Comment by yellowcap** [comment]
@ArnaudLevaufre thanks for reporting this.

Your problem is probably related to python3 unicode differences, which are picked up by the migrations framework. So those migrations are not really significant on the DB level. 

https://docs.djangoproject.com/en/1.9/topics/migrations/#supporting-python-2-and-3

I am aware of this and was working on integrating those changes for the next release. I was working on this for a while and finally submitted the new release (0.2) this morning. These migrations are part of the package now, so the problem you see should be solved with version 0.2.

Note that there is over a year worth of work between the last release and the new one I just submitted. So the package has changed quite a bit, it should be more stable now. Please let me know if you have any troubles with the update or if you have any other issues.

**Comment by ArnaudLevaufre** [comment]
Thanks a lot, it's working fine.

**Comment by yellowcap** [comment]
Glad to know that it works now. Please reach out if you find further issues or if you have questions about how to use it. I am always looking for feedback on the package. Thanks!
